/*
 * To change license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listname;

import java.util.Random;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author User
 */
public class FormLinkedList extends javax.swing.JFrame {
    Connection myConObj = null; 
    Statement myStatObj = null;
    ResultSet myResObj = null;
    PatientInfo PI = new PatientInfo();
    int panjang;
    int de, piss = 1;
    private String level;
    private String payment;
    private static final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
    private static final DateTimeFormatter stf = DateTimeFormatter.ofPattern("HH:mm:ss");
    public FormLinkedList() {
        initComponents();
        selectionall();
       
    }
    
    public void selectionall(){
        try{
     myConObj = DriverManager.getConnection("jdbc:derby://localhost:1527/MyDatabase", "zarifah", "123");
     myStatObj = myConObj.createStatement();
     myResObj = myStatObj.executeQuery("Select * from zarifah.MYTABLE");
     MyTable1.setModel(DbUtils.resultSetToTableModel(myResObj));
     
    } catch(SQLException e){
        e.printStackTrace();
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtID_no = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddDB = new javax.swing.JButton();
        btnGenerateID = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIC_no = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtCode = new javax.swing.JTextField();
        btnUpdateDB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnDisplay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();
        btnAddedLinkedList = new javax.swing.JButton();
        btnSorting = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JRYes = new javax.swing.JRadioButton();
        JRNo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MyTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtNameMouseReleased(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 185, -1));

        txtID_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_noActionPerformed(evt);
            }
        });
        jPanel1.add(txtID_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 101, 97, -1));

        jLabel1.setText("Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel2.setText("ID No :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        btnAddDB.setText("Add ");
        btnAddDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDBActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 469, 60, -1));

        btnGenerateID.setText("Generate ID");
        btnGenerateID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateIDActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerateID, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 100, -1, -1));

        jLabel3.setText("Address :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel4.setText("IC number :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setText("Date Of Birth :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));
        jPanel1.add(txtIC_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 115, -1));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane3.setViewportView(txtAddress);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 198, 99));
        jPanel1.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 111, -1));

        btnUpdateDB.setText("Update");
        btnUpdateDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDBActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 435, -1, -1));

        jLabel6.setText("Phone Number :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 111, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        jPanel2.add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 11, -1, -1));

        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        jScrollPane1.setViewportView(txtDisplay);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 45, 180, 240));

        btnAddedLinkedList.setText("Add LinkedList");
        btnAddedLinkedList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddedLinkedListActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddedLinkedList, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 442, -1, -1));

        btnSorting.setText("Sorting");
        btnSorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortingActionPerformed(evt);
            }
        });
        jPanel2.add(btnSorting, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 442, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listname/HOS9.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 280, 580));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 0, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("level 1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 10, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("level 2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 10, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("level 3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("level 4");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 51, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("level 5");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 51, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("level 6");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        jButton2.setText("Main");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 469, -1, -1));

        jLabel7.setText("Ordinary Ward :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 19, -1, -1));

        jLabel8.setText("Emergency Ward :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 51, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("yyyy-mm-dd");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 393, 83, -1));

        jLabel13.setText("Down Payment :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        JRYes.setText("yes");
        JRYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRYesActionPerformed(evt);
            }
        });
        jPanel1.add(JRYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        JRNo.setText("no");
        JRNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRNoActionPerformed(evt);
            }
        });
        jPanel1.add(JRNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        jTabbedPane1.addTab("Register Form", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MyTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "IC", "Patient Address", "Phone Number", "Date Of Birth"
            }
        ));
        jScrollPane2.setViewportView(MyTable1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 717, 170));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listname/HOS6.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 550));

        jTabbedPane1.addTab("View Table", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here
         try {
            txtDisplay.setText("");
            String blah = PI.ReturnName().pop().toString();
            PI.ReturnName().add(blah);
            txtDisplay.append("Name : " + blah + "\n");
            String hah = PI.ReturnAddress().pop().toString();
            PI.ReturnAddress().add(hah);
            txtDisplay.append("Address: " + hah + "\n");
            String kepas = PI.ReturnCode().pop().toString();
            txtDisplay.append("Date of Birth: " + kepas + "\n");
            PI.ReturnCode().add(kepas);
            String ids = PI.ReturnIC_no().pop().toString();
            txtDisplay.append("IC No: " + ids + "\n");
            PI.ReturnIC_no().add(ids);
            String phone = PI.ReturnPhoneNo().pop().toString();
            txtDisplay.append("Phone No: " + ids + "\n");
            PI.ReturnPhoneNo().add(ids);
            
              
            //String idx =PI.ReturnID_no().pop().toString();
            //txtDisplay.append("ID No: " + idx + "\n");
            //PI.ReturnID_no().add(idx);
           

            txtDisplay.append("");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Can't reach");
        }
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnUpdateDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDBActionPerformed
       
        try{
            String sql="update zarifah.MYTABLE set NAME = '"+txtName.getText()+"'"+",ICNUMBER = '"+txtIC_no.getText()+"'"+",PATIENTADDRESS = '"+txtAddress.getText()+"'"+",PHONENUMBER = '"+txtPhone.getText()+"'"+",DATEOFBIRTH = '"+txtCode.getText()+"'"+"where IDNUMBER = "+txtID_no.getText();
            Statement update = myConObj.createStatement();
            update.executeUpdate(sql);

        }catch(SQLException e){
            e.printStackTrace();

        }
        selectionall();
    }//GEN-LAST:event_btnUpdateDBActionPerformed

    private void btnGenerateIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateIDActionPerformed
        // TODO add your handling code here:
        Random rnd=new Random();
        int de=rnd.nextInt(999999-100000+1)+100000;
        txtID_no.setText(String.valueOf(de));
    }//GEN-LAST:event_btnGenerateIDActionPerformed

    private void btnAddDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDBActionPerformed
        // TODO add your handling code here:
        try{ 
            Date i;
            LocalDateTime now = LocalDateTime.now();   
            String id = txtID_no.getText();
            String name = txtName.getText();
            String ic = txtIC_no.getText();
            String address = txtAddress.getText();
            String Phone = txtPhone.getText();
            String date_of_birth = txtCode.getText();
            PreparedStatement add = myConObj.prepareStatement("insert into zarifah.MYTABLE values (?,?,?,?,?,?,?,?,?,?)");
            add.setString(1, id);
            add.setString(2, name);
            add.setString(3, ic);
            add.setString(4, address);
            add.setString(5, Phone);
            add.setString(6, date_of_birth);
            add.setString(7, dtf.format(now));
            add.setString(8, stf.format(now));
            add.setString(9, level);
            add.setString(10, payment);
            int row = add.executeUpdate();

        }   catch (SQLException ex) {
            ex.printStackTrace();
        }

        selectionall();
        
        
    }//GEN-LAST:event_btnAddDBActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MAIN().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAddedLinkedListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddedLinkedListActionPerformed
        // TODO add your handling code here:
        if (jRadioButton1.isSelected()) {
            // jRadioButton2.setSelected(false);
            panjang = panjang + 3;
        } else if (jRadioButton2.isSelected()) {
            //jRadioButton1.setSelected(false);
            panjang = panjang + 6;
        } else if (jRadioButton5.isSelected()) {
            panjang = panjang + 9;
        }

        if (jRadioButton3.isSelected()) {
            panjang = panjang + 12;
        } else if (jRadioButton4.isSelected()) {
            panjang = panjang + 15;
        } else if (jRadioButton6.isSelected()) {
            panjang = panjang + 18;
        }
        PI.Info(txtName.getText(), txtAddress.getText(), txtIC_no.getText(), txtCode.getText(), txtPhone.getText(),this.de, this.panjang);
        txtName.setText("");
        txtAddress.setText("");
        txtIC_no.setText("");
        txtCode.setText("");
        txtPhone.setText("");
        txtID_no.setText("");
        

        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jRadioButton5.setSelected(false);
        jRadioButton6.setSelected(false);

        panjang = 0;
    }//GEN-LAST:event_btnAddedLinkedListActionPerformed

    private void btnSortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortingActionPerformed
        // TODO add your handling code here:
          try {
            int ketah = PI.Returnasdf().size();
            System.out.println(PI.Returnasdf().size());
            int[] nama = new int[PI.Returnasdf().size()];
            String[] umur = new String[PI.ReturnName().size()];
            String[] deses = new String[PI.ReturnAddress().size()];
            String[] ic = new String[PI.ReturnIC_no().size()];
            String[] code = new String[PI.ReturnCode().size()];
            String[] phone = new String[PI.ReturnPhoneNo().size()];
            int[] id = new int[PI.ReturnID_no().size()];
            for (int i = 0; i < ketah; i++) {
                // txtDisplay.remove(nama[i] );   
                nama[i] = (int) PI.Returnasdf().pop();
                umur[i] = (String) PI.ReturnName().pop();
                deses[i] = (String) PI.ReturnAddress().pop();
                ic[i] = (String) PI.ReturnIC_no().pop();
                code[i] = (String) PI.ReturnCode().pop();
                phone[i] = (String) PI.ReturnPhoneNo().pop();
                id[i] = (int) PI.ReturnID_no().pop();

                txtDisplay.setText("");
                System.out.print(nama[i]);
                System.out.println("" + umur[i]);
                System.out.println("" + ic[i]);
            }

            for (int m = 0; m < (ketah - 1); m++) {
                for (int j = 0; j < (ketah - m - 1); j++) {
                    if (nama[j] > nama[j + 1]) {
                        // swap temp and arr[i]
                        int nama1 = nama[j];
                        String umur1 = umur[j];
                        String deses1 = deses[j];
                        String ic1 = ic[j];
                        String code1 = code[j];
                        int id1 = id[j];
                        nama[j] = nama[j + 1];
                        umur[j] = umur[j + 1];
                        deses[j] = deses[j + 1];
                        ic[j] = ic[j + 1];
                        code[j] = code[j + 1];
                        id[j] = id[j + 1];
                        nama[j + 1] = nama1;
                        umur[j + 1] = umur1;
                        deses[j + 1] = deses1;
                        ic[j + 1] = ic1;
                        code[j + 1] = code1;
                        id[j + 1] = id1;

                    }
                }
            }

           
            for (int i = ketah - 1; i >= 0; i--) {
                
                PI.Returnasdf().push(nama[i]);
                PI.ReturnName().push(umur[i]);
                PI.ReturnCode().push(code[i]);
                PI.ReturnIC_no().push(ic[i]);
                PI.ReturnAddress().push(deses[i]);
                PI.ReturnPhoneNo().push(deses[i]);
                PI.ReturnID_no().push(id[i]);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Can't reach");

        }
    }//GEN-LAST:event_btnSortingActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
                if (jRadioButton1.isSelected()) {
            jRadioButton2.setSelected(false);
            jRadioButton5.setSelected(false);
          
            
        }       level = "1";
             
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton2.isSelected()) {
            jRadioButton1.setSelected(false);
            jRadioButton5.setSelected(false);
               
        }        level = "2";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton3.isSelected()) {
            jRadioButton4.setSelected(false);
            jRadioButton6.setSelected(false);
                
        } level = "3";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton4.isSelected()) {
            jRadioButton3.setSelected(false);
            jRadioButton6.setSelected(false);
          
        }  level = "4";
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton5.isSelected()) {
            jRadioButton1.setSelected(false);
            jRadioButton2.setSelected(false);
             
        }   level = "5";
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        if (jRadioButton6.isSelected()) {
            jRadioButton4.setSelected(false);
            jRadioButton3.setSelected(false);
                
        }  level = "6";
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void txtID_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_noActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtID_noActionPerformed

    private void JRYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRYesActionPerformed
        // TODO add your handling code here:
        payment = "YES";
    }//GEN-LAST:event_JRYesActionPerformed

    private void JRNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRNoActionPerformed
        // TODO add your handling code here:
          payment = "NO";
    }//GEN-LAST:event_JRNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLinkedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLinkedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLinkedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLinkedList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLinkedList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRNo;
    private javax.swing.JRadioButton JRYes;
    private javax.swing.JTable MyTable1;
    private javax.swing.JButton btnAddDB;
    private javax.swing.JButton btnAddedLinkedList;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnGenerateID;
    private javax.swing.JButton btnSorting;
    private javax.swing.JButton btnUpdateDB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextArea txtDisplay;
    private javax.swing.JTextField txtIC_no;
    private javax.swing.JTextField txtID_no;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    private void filter(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
