/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listname;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author User
 */
public class Report extends javax.swing.JFrame {
    private static final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
    private static final DateTimeFormatter stf = DateTimeFormatter.ofPattern("HH:mm:ss");
    Connection myConObj = null; 
    Statement myStatObj = null;
    ResultSet myResObj = null;
    PatientInfo PI = new PatientInfo();
    private Object entry;
    String replacedStr = "DONE";
        
    FormLinkedList FLL =new FormLinkedList();
    
    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
         Selectionall();
    }
    public void Selectionall(){
        try{
     myConObj = DriverManager.getConnection("jdbc:derby://localhost:1527/MyDatabase", "zarifah", "123");
     myStatObj = myConObj.createStatement();
     myResObj = myStatObj.executeQuery("Select * from zarifah.MYTABLE2");
     MyTable2.setModel(DbUtils.resultSetToTableModel(myResObj));
     
    } catch(SQLException e){
        e.printStackTrace();
     }
       
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtName1 = new javax.swing.JTextField();
        txtID_no1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIC_no1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress1 = new javax.swing.JTextArea();
        txtCode1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPhone1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        txtNextAppoinment = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnDeleteDB = new javax.swing.JButton();
        btnUpdateDB = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MyTable2 = new javax.swing.JTable();
        txtSearch1 = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        txtDisplay1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtName1MouseReleased(evt);
            }
        });
        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 185, -1));
        jPanel1.add(txtID_no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 97, -1));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 103, -1, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel2.setText("ID No :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 65, -1, -1));

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Address :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel4.setText("IC number :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 141, -1, -1));

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Date Of Birth :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));
        jPanel1.add(txtIC_no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 115, -1));

        txtAddress1.setColumns(20);
        txtAddress1.setRows(5);
        jScrollPane3.setViewportView(txtAddress1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 198, 99));
        jPanel1.add(txtCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 111, -1));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Phone Number :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        txtPhone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhone1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 111, -1));

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Description:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Next Appoinment :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        jLabel12.setText("REPORT");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 180, 60));
        jPanel1.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 210, 40));

        txtNextAppoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNextAppoinmentActionPerformed(evt);
            }
        });
        jPanel1.add(txtNextAppoinment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 100, 30));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 521, -1, -1));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 521, -1, -1));

        btnDeleteDB.setText("Delete");
        btnDeleteDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDBActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 521, -1, -1));

        btnUpdateDB.setText("Update");
        btnUpdateDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDBActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 521, -1, -1));

        jButton4.setText("MAIN MENU");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 521, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("yyyy-mm-dd");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 83, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listname/HOSRUANGLEK2.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 620));

        jTabbedPane1.addTab("Report Form", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 204, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MyTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Number", "Name", "IC Number", "Address", "Date Of Birth ", "Phone Number", "Description", "Next Appoinment"
            }
        ));
        jScrollPane2.setViewportView(MyTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 141, 723, 124));

        txtSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtSearch1MouseReleased(evt);
            }
        });
        jPanel3.add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 339, 211, -1));

        btnSearch1.setText("search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 338, -1, -1));

        txtDisplay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplay1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtDisplay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 367, 211, 29));

        jButton3.setText("MAIN MENU");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 458, -1, -1));

        jLabel9.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel9.setText("List name of discharge patient:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 102, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/listname/HOS9_1.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 620));

        jTabbedPane1.addTab("View table", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtName1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtName1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1MouseReleased

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void txtPhone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhone1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        myConObj = DriverManager.getConnection("jdbc:derby://localhost:1527/MyDatabase", "zarifah", "123");
        myStatObj = myConObj.createStatement();
        myResObj = myStatObj.executeQuery("SELECT * FROM MYTABLE WHERE NAME='"+txtName1.getText()+"'");
        if (myResObj.next()){
            txtID_no1.setText(myResObj.getString("IDNUMBER"));
            txtAddress1.setText(myResObj.getString("PATIENTADDRESS"));
            txtIC_no1.setText(myResObj.getString("ICNUMBER"));
            txtCode1.setText(myResObj.getString("DATEOFBIRTH"));
            txtPhone1.setText(myResObj.getString("PHONENUMBER"));
            
        }else{
            JOptionPane.showMessageDialog(null, "Can't reach");
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNextAppoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNextAppoinmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNextAppoinmentActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            LocalDateTime now = LocalDateTime.now();   
            String id = txtID_no1.getText();
            String name = txtName1.getText();
            String ic = txtIC_no1.getText();
            String address = txtAddress1.getText();
            String Phone = txtPhone1.getText();
            String date_of_birth = txtCode1.getText();
            String description = txtDescription.getText();
            String NextAppoinment = txtNextAppoinment.getText();
            PreparedStatement add = myConObj.prepareStatement("insert into zarifah.MYTABLE2 values (?,?,?,?,?,?,?,?,?,?,?)");
            add.setString(1, id);
            add.setString(2, name);
            add.setString(3, ic);
            add.setString(4, address);
            add.setString(5, date_of_birth);
            add.setString(6, Phone);
            add.setString(7, description);
            add.setString(8, NextAppoinment);
            add.setString(9, stf.format(now));
            add.setString(10,dtf.format(now));
            add.setString(11, replacedStr);
            int row = add.executeUpdate();

        }   catch (SQLException ex) {
            ex.printStackTrace();
        }

        Selectionall();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDeleteDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDBActionPerformed
        // TODO add your handling code here:
        try {
            String sql="Delete from zarifah.MYTABLE where IDNUMBER ="+txtID_no1.getText();
            Statement add=myConObj.createStatement();
            add.executeUpdate(sql);
            txtID_no1.setText("");
            txtName1.setText("");
            txtAddress1.setText("");
            txtIC_no1.setText("");
            txtPhone1.setText("");
            txtCode1.setText("");

        }catch(SQLException e)
        {e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteDBActionPerformed

    private void btnUpdateDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDBActionPerformed
        // Null is not zero. Null is not an empty string.
        //Null is not a value at all.
        //Most importantly for our discussion, one null value does not equal any other null value.
        try{
            String sql="update zarifah.MYTABLE set NAME = '"+txtName1.getText()+"'"+",ICNUMBER = '"+txtIC_no1.getText()+"'"+",PATIENTADDRESS = '"+txtAddress1.getText()+"'"+",PHONENUMBER = '"+txtPhone1.getText()+"'"+",DATEOFBIRTH = '"+txtCode1.getText()+"'"+"where IDNUMBER = "+txtID_no1.getText();
            Statement update = myConObj.createStatement();
            update.executeUpdate(sql);

        }catch(SQLException e){
            e.printStackTrace();

        }
        Selectionall();
    }//GEN-LAST:event_btnUpdateDBActionPerformed

    private void txtSearch1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearch1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch1MouseReleased

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
              try{ HashMap<String,String> HMap;
        HMap = new HashMap <String,String>();        
        myConObj = DriverManager.getConnection("jdbc:derby://localhost:1527/MyDatabase", "zarifah", "123");
        myStatObj = myConObj.createStatement();
        myResObj = myStatObj.executeQuery("SELECT * FROM MYTABLE WHERE NAME='"+txtSearch1.getText()+"'");
        if (myResObj.next()){
            HMap.put("ID NO ", myResObj.getString("IDNUMBER"));
            
          for(Map.Entry <String,String> entry : HMap.entrySet()){
              String key = entry.getKey();
              String value= entry.getValue();
              txtDisplay1.setText(key+":"+value); }
        }else{ JOptionPane.showMessageDialog(null, "Can't reach");}
        }catch(Exception e){
            e.printStackTrace();}                                          



    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void txtDisplay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplay1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      new MAIN().setVisible(true);
      dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      new MAIN().setVisible(true);
      dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MyTable2;
    private javax.swing.JButton btnDeleteDB;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JButton btnUpdateDB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtAddress1;
    private javax.swing.JTextField txtCode1;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtDisplay1;
    private javax.swing.JTextField txtIC_no1;
    private javax.swing.JTextField txtID_no1;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtNextAppoinment;
    private javax.swing.JTextField txtPhone1;
    private javax.swing.JTextField txtSearch1;
    // End of variables declaration//GEN-END:variables
}
